services:
  ctr-zbx-proxy:
    image: zabbix/zabbix-proxy-sqlite3:alpine-7.4-latest
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    environment:
      - ZBX_HOSTNAME=${ZBX_HOSTNAME}
      - ZBX_SERVER_HOST=${ZBX_SERVER_HOST}
    volumes:
      - ${VOL_TIMEZONE}
      - ${VOL_LOCALTIME}
      - ${VOL_SQLITE}
    ports:
      - "10051:10051"
    networks:
      network-share:
        ipv4_address: ${IPV4_PROXY}

networks:
  network-share:
    external: true
